apiVersion: batch/v1
kind: Job
metadata:
  name: initializer
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: initializer
          image: forcad-initializer
          envFrom:
            - secretRef:
                name: forcad-postgres-secret
            - secretRef:
                name: forcad-rabbitmq-secret
            - secretRef:
                name: forcad-redis-secret
          env:
            - name: CONFIG_PATH
              value: "/config/config.yml"
          volumeMounts:
            - name: config-file
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: config-file
          secret:
            secretName: forcad-config-file
            items:
              - key: content
                path: config.yml
      restartPolicy: OnFailure
