apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    appType: database
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.2
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: forcad-postgres-secret

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
