apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    appType: broker
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.8.3-management-alpine
          ports:
            - containerPort: 5672
          envFrom:
            - secretRef:
                name: forcad-rabbitmq-secret

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
