apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticker
  labels:
    appType: single
spec:
  selector:
    matchLabels:
      app: ticker
  template:
    metadata:
      labels:
        app: ticker
    spec:
      containers:
        - name: ticker
          image: forcad-service
          env:
            - name: SERVICE
              value: "ticker"
          envFrom:
            - secretRef:
                name: forcad-postgres-secret
            - secretRef:
                name: forcad-rabbitmq-secret
            - secretRef:
                name: forcad-redis-secret
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
