apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: forcad-postgres-secret
            - secretRef:
                name: forcad-rabbitmq-secret
            - secretRef:
                name: forcad-redis-secret
          env:
            - name: PORT
              value: "5000"
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 1000m
              memory: 500Mi
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            httpGet:
              port: 5000
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 20
            httpGet:
              port: 5000
