apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: forcad-service
      context: .
      docker:
        dockerfile: ./docker_config/services/Dockerfile
    - image: forcad-initializer
      context: .
      docker:
        dockerfile: ./docker_config/initializer/Dockerfile
    - image: forcad-celery
      context: .
      docker:
        dockerfile: ./docker_config/celery/Dockerfile
    - image: forcad-nginx
      context: .
      docker:
        dockerfile: ./docker_config/nginx/Dockerfile
        buildArgs:
          DNS_RESOLVER: 127.0.0.1
  tagPolicy:
    gitCommit: { }
  local:
    useBuildkit: true
deploy:
  kustomize:
    paths: [ "deploy" ]
