admin:
  password: 4c24c1cabd58d90a
  username: forcad
game:
  checkers_path: /checkers/
  default_score: 2500.0
  env_path: ''
  flag_lifetime: 5
  game_hardness: 10.0
  inflation: true
  mode: classic
  round_time: 20
  start_time: 2023-04-01 12:30:00
  timezone: Europe/Moscow
  volga_attacks_mode: false
storages:
  db:
    dbname: forcad
    host: postgres
    password: 4c24c1cabd58d90a
    port: 5432
    user: forcad
  rabbitmq:
    host: rabbitmq
    password: 4c24c1cabd58d90a
    port: 5672
    user: forcad
    vhost: forcad
  redis:
    db: 0
    host: redis
    password: 4c24c1cabd58d90a
    port: 6379
tasks:
- checker: 5Go/checker.py
  checker_timeout: 10
  checker_type: hackerdom
  gets: 2
  name: 5Go
  places: 5
  puts: 2
- checker: modelrna/checker.py
  checker_timeout: 10
  checker_type: hackerdom
  gets: 2
  name: modelrna
  places: 5
  puts: 2
- checker: sputnik_v8/checker.py
  checker_timeout: 10
  checker_type: hackerdom
  gets: 2
  name: modelrna
  places: 5
  puts: 2
- checker: virush/checker.py
  checker_timeout: 10
  checker_type: hackerdom
  gets: 2
  name: modelrna
  places: 5
  puts: 2
- checker: kuar/checker.py
  checker_timeout: 10
  checker_type: hackerdom
  gets: 2
  name: kuar
  places: 5
  puts: 2
- checker: vacc_ex/checker.py
  checker_timeout: 10
  checker_type: hackerdom
  gets: 2
  name: vacc_ex
  places: 5
  puts: 2
teams:
- highlighted: false
  ip: 10.152.34.240
  name: TeamTest
